# Generated by Django 4.1.4 on 2023-01-12 12:21

from django.db import migrations
import wagtail.blocks
import wagtail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventpage',
            name='event_text',
            field=wagtail.fields.StreamField([('event_text', wagtail.blocks.StructBlock([('title', wagtail.blocks.CharBlock()), ('text', wagtail.blocks.TextBlock())]))], blank=True, null=True, use_json_field=True),
        ),
    ]
