# Generated by Django 4.1.4 on 2023-01-11 08:46

from django.db import migrations
import wagtail.blocks
import wagtail.fields
import wagtail.images.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_remove_homepage_body_homepage_banner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homepage',
            name='banner',
            field=wagtail.fields.StreamField([('banner', wagtail.blocks.StructBlock([('title', wagtail.blocks.CharBlock()), ('text', wagtail.blocks.TextBlock(help_text='maximum charachter limit is 400.', max_length=400, required=True)), ('image', wagtail.images.blocks.ImageChooserBlock(required=False)), ('button', wagtail.blocks.PageChooserBlock(required=False))]))], blank=True, null=True, use_json_field=True),
        ),
    ]
