# Generated by Django 4.1.4 on 2023-01-11 10:42

from django.db import migrations, models
import wagtail.blocks
import wagtail.fields
import wagtail.images.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_alter_homepage_banner'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='testimonial',
            field=wagtail.fields.StreamField([('testimonial', wagtail.blocks.StructBlock([('name', wagtail.blocks.CharBlock(required=True)), ('qualification', wagtail.blocks.CharBlock(required=False)), ('message', wagtail.blocks.RichTextBlock(required=True)), ('image', wagtail.images.blocks.ImageChooserBlock())]))], blank=True, null=True, use_json_field=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='testimonial_text',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
