# Generated by Django 4.1.4 on 2023-01-11 11:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_aboutpage'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AboutPage',
        ),
    ]
