# Generated by Django 4.1.4 on 2023-01-12 11:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0002_ourteam'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aboutpage',
            name='image',
        ),
    ]
